#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <module_path> <network>"
  exit 1
fi

MODULE_NAME="$1"
NETWORK="$2"

npx hardhat ignition deploy ignition/modules/"$MODULE_NAME".ts --network "$NETWORK" --parameters ignition/parameters.json